name: Stream to YouTube

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Install FFmpeg
        run: sudo apt install ffmpeg -y

      - name: Start Streaming
        run: |
          ffmpeg -re -i "رابط_البث_M3U8_هنا" \
          -c:v copy -c:a copy -f flv "rtmp://a.rtmp.youtube.com/live2/مفتاح_البث_الخاص_بك"
