name: Kick to Restream Auto-Monitor

on:
  workflow_dispatch:

jobs:
  keep-streaming:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Environment
        run: |
          sudo apt update
          sudo apt install -y ffmpeg python3-pip
          pip3 install --upgrade --force-reinstall git+https://github.com/streamlink/streamlink.git

      - name: Continuous Stream Monitor & Broadcaster
        run: |
          chmod +x stream.sh
          echo "تم تفعيل نظام المراقبة التلقائية لقناة (id7o)..."
          
          while true; do
            if streamlink "https://kick.com/id7o" > /dev/null 2>&1; then
              echo "تم رصد البث المباشر الآن! جاري نقل البث برستريم..."
              ./stream.sh
              echo "توقف البث، جاري إعادة تفعيل الرادار..."
            else
              echo "القناة غير مبثّة حالياً... يتم إعادة الفحص خلال 30 ثانية..."
            fi
            sleep 30
          done
